FROM python:3.12.7-slim

WORKDIR /app
RUN useradd --create-home appuser

ENV PYTHONPATH="${PYTHONPATH}:/app/app"
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
COPY ../requirements/prod.txt ./requirements/prod.txt
RUN pip install --no-cache-dir -r ./requirements/prod.txt

COPY .. .

USER appuser